import '../styles/globals.css'
import 'antd/dist/antd.css';
import type { AppProps } from 'next/app'
import { ApolloProvider } from '@apollo/client';
import { GRAPHQL_USER } from '../services/GraphQL'
import { ContextProvider } from '../context';
import {TopHeader} from '../libs/shared-components'
import Head from 'next/head';

function MyApp({ Component,router, pageProps }: AppProps) {
 
  return   <ApolloProvider client={GRAPHQL_USER.CLIENT}>
              <Head>
                  <title>Air Call</title>
                  <meta name="description" content="Generated by create next app" />
                  <link rel="icon" href="/favicon.png" />
              </Head>
              <ContextProvider>
                {![
                '/auth/sign-in'
                ].includes(router.route) &&   <TopHeader />}
                <Component {...pageProps} />
              </ContextProvider>
             
           </ApolloProvider>
}





export default MyApp

